### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by thienohs** [markusenglund/react-kanban#8]
Dear developers,
We have followed the instruction to install the full version and encounter the below error due to node-zopli. The simple version is however working as expected.

git clone https://github.com/yogaboll/react-kanban.git
cd react-kanban
npm install

```
34550 verbose stack Error: node-zopfli@2.0.2 install: `node-pre-gyp install --fallback-to-build`
34550 verbose stack Exit status 1
34550 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
34550 verbose stack     at EventEmitter.emit (events.js:182:13)
34550 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
34550 verbose stack     at ChildProcess.emit (events.js:182:13)
34550 verbose stack     at maybeClose (internal/child_process.js:962:16)
34550 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:249:5)
34551 verbose pkgid node-zopfli@2.0.2
34552 verbose cwd /Users/___/Documents/ReactProjects/___/react-kanban
34553 verbose Darwin 17.7.0
34554 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
34555 verbose node v10.8.0
34556 verbose npm  v6.2.0
34557 error code ELIFECYCLE
34558 error errno 1
34559 error node-zopfli@2.0.2 install: `node-pre-gyp install --fallback-to-build`
34559 error Exit status 1
34560 error Failed at the node-zopfli@2.0.2 install script.
34560 error This is probably not a problem with npm. There is likely additional logging output above.
34561 verbose exit [ 1, true ]
```

**Comment by thienohs** [comment]
It'll be working if removed the webpack plugin below in package.json
**"zopfli-webpack-plugin": "^0.1.0"**

And then remove the plugin's related codes in **webpack.config.client.js**
